name: Speculator CI

on: [push]

jobs:
    build:
        name: compile-speculator
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: configure
              run: cmake $SPEC_H -B$SPEC_B -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$SPEC_I -G "Ninja"
              env:
                  SPEC_H=./
                  SPEC_B=./build
                  SPEC_I=./install

