name: Speculator CI

on: [push]

jobs:
    build:
        name: compile-speculator
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
                compiler: [gcc, clang]
        steps:
            - uses: actions/checkout@v2

            - name: dependencies
              run: sudo apt install cmake gcc g++ clang libjson-c-dev libpfm4-dev ninja-build python-sqlalchemy cmake nasm

            - name: configure
              run: cmake $SPEC_H -B$SPEC_B -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$SPEC_I -G "Ninja"
              env:
                  SPEC_H: ./
                  SPEC_B: ./build
                  SPEC_I: ./install

            - name: compile
              run: ninja -C $SPEC_B
              env:
                  SPEC_B: ./build

            - name: install
              run: ninja -C $SPEC_B install
              env:
                  SPEC_B: ./build

            - name: Return Stack Buffer example
              run: $SPEC_H/scripts/cr_inc_snip.py --output $SPEC_H/tests/rsb_deep_stack $SPEC_H/examples/rsb/rsb_fill_deep_stack.json $SPEC_H/examples/rsb/rsb_fill_deep_stack.asm && cmake $SPEC_H -B$SPEC_B -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$SPEC_I -G "Ninja" && ninja -C $SPEC_B install && rm -rf $SPEC_H/tests/rsb_deep_stack && rm -rf $SPEC_I/* && rm -rf $SPEC_B/*
              env:
                  SPEC_H: ./
                  SPEC_B: ./build
                  SPEC_I: ./install

            - name: Speculation of Nested Branches example
              run: cp $SPEC_H/examples/speculation_in_speculation/speculation_in_speculation_in_speculation.asm $SPEC_H/tests && cmake $SPEC_H -B$SPEC_B -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$SPEC_I -G "Ninja" && ninja -C $SPEC_B install && rm -rf $SPEC_H/tests/speculation_in_speculation_in_speculation.asm && rm -rf $SPEC_I/* && rm -rf $SPEC_B/*
              env:
                  SPEC_H: ./
                  SPEC_B: ./build
                  SPEC_I: ./install

            - name: Speculative Execution Across System Calls example
              run: cp $SPEC_H/examples/syscall_speculation/syscall_speculation_baseline.asm $SPEC_H/tests && $SPEC_H/scripts/cr_inc_snip.py --output $SPEC_H/tests/syscall_speculation $SPEC_H/examples/syscall_speculation/syscall_speculation.json $SPEC_H/examples/syscall_speculation/syscall_speculation.asm && cp $SPEC_H/examples/speculation_in_speculation/speculation_in_speculation_in_speculation.asm $SPEC_H/tests && cmake $SPEC_H -B$SPEC_B -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$SPEC_I -G "Ninja" && ninja -C $SPEC_B install && rm -rf $SPEC_H/tests/syscall_speculation && rm -rf $SPEC_H/tests/syscall_speculation_baseline.asm && rm -rf $SPEC_H/tests/*.asm && rm -rf $SPEC_I/* && rm -rf $SPEC_B/*
              env:
                  SPEC_H: ./
                  SPEC_B: ./build
                  SPEC_I: ./install

            - name: Flushing the Cache example
              run: cp $SPEC_H/examples/clflush_in_speculation/clflush_in_speculation_cached.asm $SPEC_H/tests/ && cp $SPEC_H/examples/clflush_in_speculation/clflush_in_speculation_uncached.asm $SPEC_H/tests/  && cmake $SPEC_H -B$SPEC_B -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$SPEC_I -G "Ninja" && ninja -C $SPEC_B install && rm -rf $SPEC_H/tests/clflush_in_speculation_cached.asm $SPEC_H/tests/clflush_in_speculation/clflush_in_speculation_uncached.asm && rm -rf $SPEC_I/* && rm -rf $SPEC_B/*
              env:
                  SPEC_H: ./
                  SPEC_B: ./build
                  SPEC_I: ./install

            - name: Speculation Window Size example
              run: cp $SPEC_H/examples/v1_various_cond_cycles/*.asm $SPEC_H/tests/ && cp $SPEC_H/examples/v2_various_uncond_cycles/*.asm $SPEC_H/tests/ &&  $SPEC_H/scripts/cr_inc_snip.py --output $SPEC_H/tests/v4_cycles $SPEC_H/examples/v4_cycles/v4_cycles.json $SPEC_H/examples/v4_cycles/v4_cycles.asm && cmake $SPEC_H -B$SPEC_B -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$SPEC_I -G "Ninja" && ninja -C $SPEC_B install && rm -rf $SPEC_H/tests/*.asm $SPEC_H/tests/v4_cycles && rm -rf $SPEC_I/* && rm -rf $SPEC_B/*
              env:
                  SPEC_H: ./
                  SPEC_B: ./build
                  SPEC_I: ./install

            - name: Speculation Stopper example
              run: $SPEC_H/scripts/cr_inc_snip.py --output $SPEC_H/tests/speculation_stopper $SPEC_H/examples/speculation_stopper/speculation_stopper.json $SPEC_H/examples/speculation_stopper/speculation_stopper.asm && cmake $SPEC_H -B$SPEC_B -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$SPEC_I -G "Ninja" && ninja -C $SPEC_B install && rm -rf $SPEC_H/tests/speculation_stopper && rm -rf $SPEC_I/* && rm -rf $SPEC_B/*
              env:
                  SPEC_H: ./
                  SPEC_B: ./build
                  SPEC_I: ./install
